# esto es la imagen limpia que queremos usar
FROM openjdk:17-jdk-alpine
# comando que copiara nuestra aplicacion dentro de la imagen
COPY target/webclient-1.jar webclient-1.jar
# es lo que ejecutara dentro de la imagen la aplicacion
ENTRYPOINT ["java","-jar","/webclient-1.jar"]
#expone el puerto
EXPOSE 8084